// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "total title",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"layout"}>
        header
        {children}
        footer
      </body>
    </html>
  );
}
